# -*- coding: utf-8 -*-

# Exagerated example, tests:
#   Float/int/str TbAttributes, ie Chipload, Flutes, Material, SpindleDirection, SpindlePower
tb_naming_rules = {"shapename"  :{"ptype": "added_macro_prop",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "_",
                                  "sep_r": "_",
                                  "order": 98
                                 },
             "base_name"        :{"ptype": "added_macro_prop",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "_",
                                  "sep_r": "",
                                  "order": 99
                                 },
             # This is ONLY element with added/different properties!
             "t_auto_number"    :{"ptype": "added_macro_prop",
                                  "tb_base_nr": 30000,    # For now KISS:= user sets!! ??lookup based on shapename??
                                  "tb_dia_mult": 1000,
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 1
                                 },
             "Chipload"         :{"ptype": "TbAttributes",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "CL",
                                  "sep_left": "_",
                                  "sep_r": "_",
                                  "order": 5
                                 },
             "Flutes"           :{"ptype": "TbAttributes",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "F",
                                  "sep_left": "_",
                                  "sep_r": "",
                                  "order": 3
                                 },
             "Material"         :{"ptype": "TbAttributes",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "_",
                                  "sep_r": "_",
                                  "order": 6
                                 },
             "SpindleDirection" :{"ptype": "TbAttributes",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "_",
                                  "sep_r": "_",
                                  "order": 8
                                 },
             "SpindlePower"     :{"ptype": "TbAttributes",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "_",
                                  "sep_r": "_",
                                  "order": 7
                                 },
             "BladeThickness"   :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "CapDiameter"      :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "CapHeight"        :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "Crest"            :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "cuttingAngle"     :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "deg",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "CuttingEdgeAngle" :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "CuttingEdgeHeight":{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "Diameter"         :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "D",
                                  "sep_left": "_",
                                  "sep_r": "",
                                  "order": 2
                                 },
             "FlatRadius"       :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "Length"           :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "L",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "NeckDiameter"     :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "ND",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "NeckHeight"       :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "NH",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "NeckLength"       :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "NL",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "ShankDiameter"    :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "DS",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "TipAngle"         :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
             "TipDiameter"      :{"ptype": "TbShape",
                                  "pref_name": "",
                                  "abbrev_left": "",
                                  "abbrev_r": "",
                                  "sep_left": "",
                                  "sep_r": "",
                                  "order": 0
                                 },
        }
